### PR TITLE
CreateImageWizard: fix label spacing

### LINKED ISSUE #597: Label spacing is wrong
Spacing between labels – In mocks it is 4px between label & what is being labeled, and then 8px between the content.

image22

### PR DESCRIPTION
**Pull request by chloenayon**
Decrease the spacing below labels from 8px to 4px in accordance with the mocks.
Fixes #597

### CODE REVIEW

File: src/Components/CreateImageWizard/formComponents/TargetEnvironment.js [hunk 1]
```diff
@@ -41,7 +41,7 @@ const TargetEnvironment = ({ label, isRequired, ...props }) => {
     return (
         <>
             <FormGroup isRequired={ isRequired } label={ label } data-testid="target-select">
-                <FormGroup label={ <Text component={ TextVariants.small }>Public cloud</Text> } data-testid="target-public">
+                <FormGroup label={ <small>Public cloud</small> } data-testid="target-public">
```
Comment (jkozol) [inline src/Components/CreateImageWizard/formComponents/TargetEnvironment.js:44]: This change is unnecessary for the fix

Comment (jkozol) [inline src/Components/CreateImageWizard/formComponents/TargetEnvironment.js:44]: This change is unnecessary for the fix

**Review by jkozol — COMMENTED** [review]
Nice find on the fix. Looks good to me. I wonder if we should change all the label spacing. @katierik any thoughts? It seems other field labels have a margin of 8px. Should we change all or is this 4px spacing specific to the image output labels?


~~Also, @chloenayon can you increase the spacing between the tiles or create a seperate issue for tracking that. "8px between the content"~~

**Review by jkozol — DISMISSED** [review]

**Comment by chloenayon** [comment]
with the change: 

Screenshot from 2022-04-08 13-33-05

**Review by jkozol — APPROVED** [review]
