### PR TITLE
CreateImageWizard: fix gcp popover

### LINKED ISSUE #601: Improve GCP popover
Spacing here is off – padding on right and bottom seems small.

Content should go to right (not above). Preference order: Right, Down, Up, Left – Set flip order.

image17

### PR DESCRIPTION
**Pull request by kingsleyzissou**
Update the popover for the gcp step in the CreateImageWizard. This commit
changes the default popover position to the right of the modal.
Fixes #601 

Screenshot:
gcp_after

### CODE REVIEW

File: src/Components/CreateImageWizard/steps/googleCloud.js [hunk 1]
```diff
@@ -19,6 +19,7 @@ const PopoverInfo = ({ appendTo }) => {
         hasAutoWidth
         maxWidth='35rem'
         headerContent={ 'Valid account types' }
+        flipBehavior={['right', 'down', 'up', 'left']}
```
Comment (jkozol) [inline src/Components/CreateImageWizard/steps/googleCloud.js:22]: down should be bottom and up should be top

**Review by jkozol — CHANGES_REQUESTED** [review]

File: src/Components/CreateImageWizard/steps/googleCloud.js (hunk 1 above)
Comment (jkozol) [reply src/Components/CreateImageWizard/steps/googleCloud.js:22]: flipBehaviour can have the following options: 

'flip' \| (     \| 'top'     \| 'bottom'     \| 'left'     \| 'right'     \| 'top-start'     \| 'top-end'     \| 'bottom-start'     \| 'bottom-end'     \| 'left-start'     \| 'left-end'     \| 'right-start'     \| 'right-end'   )

Comment (kingsleyzissou) [reply src/Components/CreateImageWizard/steps/googleCloud.js:22]: > down should be bottom and up should be top
Smh thanks. Was looking at that too long and obviously didn't see it

Comment (jkozol) [reply src/Components/CreateImageWizard/steps/googleCloud.js]: haha I know that feeling

**Review by jkozol — APPROVED** [review]
lgtm!
